### ISSUE TITLE
Exception - StackOverflow

### ISSUE THREAD

**Issue by apariciom** [serilog-trace-listener/SerilogTraceListener#18]
When used in WCF. The WCF service is self-hosted.

<system.diagnostics>

    <sources>
      <source name="System.ServiceModel"
              switchValue="Information, ActivityTracing"
              propagateActivity="true">
        <listeners>
          <add name="xml" />
        </listeners>
      </source>

      <source name="System.ServiceModel.MessageLogging">
        <listeners>
          <add name="xml" />
        </listeners>
      </source>
    </sources>

    <sharedListeners>
      <add name="xml"
           type="SerilogTraceListener.SerilogTraceListener, SerilogTraceListener"
           initializeData="application-id" />
    </sharedListeners>

  </system.diagnostics>

An unhandled exception of type 'System.StackOverflowException' occurred in SMDiagnostics.dll

**Comment by nblumhardt** [comment]
Hi! Thanks for the heads-up; we'll need some more info (possibly some debugging at your end) to track this down.

As the issue here is quite old, I'll assume it's stale and close it. If there's still a problem please feel free to reopen.
