### ISSUE TITLE
.NET Core 2.0 compatibility for nuget package

### ISSUE THREAD

**Issue by hacst** [serilog-trace-listener/SerilogTraceListener#19]
I am using Serilog in a .NET Core 2.0 targeted project and want to redirect the normal tracing facilities into it using SerilogTraceListener. However since the nuget package is targeted solely at .NET 4.6.1 I get the following nuget warning:

> warning NU1701: Package 'SerilogTraceListener 3.0.10043' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

It would be great if the nuget packet could be multi-targeted to include .NET Core 2.0 support like other Serilog related packages.

Thanks.

**Comment by nblumhardt** [comment]
Thanks for the heads-up :+1: Marked `up-for-grabs`.

**Comment by hacst** [comment]
I'll see whether I can figure this out this weekend. Figure it shouldn't be too hard. Not very experience with .NET build stuff though.
