### ISSUE TITLE
Couldn't find type for class Serilog.Diagnostics.SerilogTraceListener, Serilog.Diagnostics.TraceListener.

### ISSUE THREAD

**Issue by gorkemhacioglu** [serilog-trace-listener/SerilogTraceListener#33]
Getting an error when I add listener to my tracer(System.Diagnostics.Trace).

```
var listener = new SerilogTraceListener.SerilogTraceListener();
Trace.Listeners.Add(listener);
```
Error:System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Couldn't find type for class Serilog.Diagnostics.SerilogTraceListener, Serilog.Diagnostics.TraceListener.
  
I tried to use in this way too
`var listener = new Serilog.Diagnostics.SerilogTraceListener();
` but I got an error which is "Diagnostics does not exist in the namespace 'Serilog'"

I have;
```
<system.diagnostics>
    <trace autoflush="true">
      <listeners>
        <add name="Serilog"
             type="Serilog.Diagnostics.SerilogTraceListener, Serilog.Diagnostics.TraceListener"/>
      </listeners>
    </trace>
  </system.diagnostics>
``` 
in my App.config

**Comment by augustoproiete** [comment]
@gorkemhacioglu Which version of the [SerilogTraceListener](https://www.nuget.org/packages/SerilogTraceListener/) are you using, and which .NET are you targeting? Both errors seem to indicate that the SerilogTraceListener assembly is not being referenced in the project.

**Comment by augustoproiete** [comment]
@gorkemhacioglu Are you able to put together a simple console app that reproduces the error and publish it on a repo?

**Comment by gorkemhacioglu** [comment]
I didn't get any error on a fresh project. I think there is a reference conflict in my main project. Thanks for quick response.
