### ISSUE TITLE
Disambiguate namespace/class name

### ISSUE THREAD

**Issue by nblumhardt** [serilog-trace-listener/SerilogTraceListener#4]
Using the name `SerilogTraceListener` as both the namespace and class names makes it awkward to resolve in C# code.

I think we need to rename one or the other; I'm not sure if any particular option stands out. Here is one proposal, any alternatives/suggestions would be great.

``` csharp
// assembly: Serilog.Diagnostics
namespace Serilog.Diagnostics
{
    public class SerilogTraceListener: TraceListener
    {
```

Thus `new SerilogTraceListener()` with the namespace generally inferred by VS/ReSharper, and `"Serilog.Diagnostics.TraceListener, Serilog.Diagnostics"` in XML.

(Avoiding NuGet package renames if possible for now.)

It's not necessarily conventional to package _Serilog.Diagnostics.dll_ in _SerilogTraceListener_, but since a) most XML configuration is copy/paste and b) in VS, typing _SerilogTraceListener_ will resolve to the correct class name, I think it'd be fine in practice.

Thoughts?

**Comment by CrazyPyro** [comment]
Apparently this was once known as `Serilog.Extras.TraceListener`
Perhaps 5209d49 should be reverted?  (And would it make sense for this project move under the official Serilog umbrella?)

**Comment by nblumhardt** [comment]
@CrazyPyro thanks for giving this one a nudge 👍 

I think we pretty much universally obsoleted the _Serilog.Extras.*_ naming, so moving forward to _Serilog.Diagnostics.TraceListener_ seems a bit nicer and lines up with how things are done at present. A PR would be appreciated if you're interested in having a shot at it.

I'm not against bringing it under `/serilog`, but there's not a huge motivation to do it either so I'd rather keep things as-is for now. Thanks for the input though!
